// <auto-generated />
using ApiSecciones.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSecciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230627110940_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiSecciones.Models.Seccion", b =>
                {
                    b.Property<int>("seccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("seccionId"), 1L, 1);

                    b.Property<string>("seccionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seccionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("seccionId");

                    b.ToTable("seccions");
                });
#pragma warning restore 612, 618
        }
    }
}
